import { useEffect, useState } from "react";
import { useDrop } from "react-dnd";
import Team from "../models/Team";
import Tile from "../models/Tile";
import "./Main.css";
import TeamForm from "./TeamForm";
import WordTile from "./WordTile";
import ColorTile from "./ColorTile";

const Main = () => {
  const [team1, setTeam1] = useState<Team>({
    teamName: "",
    teamColor: "red",
    teamScore: 0,
  });
  const [team2, setTeam2] = useState<Team>({
    teamName: "",
    teamColor: "blue",
    teamScore: 0,
  });
  const [gameList, setGameList] = useState<string[]>([
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
  ]);
  const [shuffledWordList, setShuffledWordList] = useState<string[]>([]);
  const [startClicked, setStartClicked] = useState(false);
  const [redScore, setRedScore] = useState(0);
  const [blueScore, setBlueScore] = useState(0);

  const [tiles, setTiles] = useState<Tile[]>([
    { id: 1, color: "red" },
    { id: 2, color: "blue" },
    { id: 3, color: "white" },
    { id: 4, color: "black" },
  ]);

  const masterWordList = [
    "AFRICA",
    "AGENT",
    "AIR",
    "ALIEN",
    "ALPS",
    "AMAZON",
    "AMBULANCE",
    "AMERICA",
    "ANGEL",
    "ANTARCTICA",
    "APPLE",
    "ARM",
    "ATLANTIS",
    "AUSTRALIA",
    "AZTEC",
    "BACK",
    "BALL",
    "BAND",
    "BANK",
    "BAR",
    "BARK",
    "BAT",
    "BATTERY",
    "BEACH",
    "BEAR",
    "BEAT",
    "BED",
    "BEIJING",
    "BELL",
    "BELT",
    "BERLIN",
    "BERMUDA",
    "BERRY",
    "BILL",
    "BLOCK",
    "BOARD",
    "BOLT",
    "BOMB",
    "BOND",
    "BOOM",
    "BOOT",
    "BOTTLE",
    "BOW",
    "BOX",
    "BRIDGE",
    "BRUSH",
    "BUCK",
    "BUFFALO",
    "BUG",
    "BUGLE",
    "BUTTON",
    "CALF",
    "CANADA",
    "CAP",
    "CAPITAL",
    "CAR",
    "CARD",
    "CARROT",
    "CASINO",
    "CAST",
    "CAT",
    "CELL",
    "CENTAUR",
    "CENTER",
    "CHAIR",
    "CHANGE",
    "CHARGE",
    "CHECK",
    "CHEST",
    "CHICK",
    "CHINA",
    "CHOCOLATE",
    "CHURCH",
    "CIRCLE",
    "CLIFF",
    "CLOAK",
    "CLUB",
    "CODE",
    "COLD",
    "COMIC",
    "COMPOUND",
    "CONCERT",
    "CONDUCTOR",
    "CONTRACT",
    "COOK",
    "COPPER",
    "COTTON",
    "COURT",
    "COVER",
    "CRANE",
    "CRASH",
    "CRICKET",
    "CROSS",
    "CROWN",
    "CYCLE",
    "CZECH",
    "DANCE",
    "DATE",
    "DAY",
    "DEATH",
    "DECK",
    "DEGREE",
    "DIAMOND",
    "DICE",
    "DINOSAUR",
    "DISEASE",
    "DOCTOR",
    "DOG",
    "DRAFT",
    "DRAGON",
    "DRESS",
    "DRILL",
    "DROP",
    "DUCK",
    "DWARF",
    "EAGLE",
    "EGYPT",
    "EMBASSY",
    "ENGINE",
    "ENGLAND",
    "EUROPE",
    "EYE",
    "FACE",
    "FAIR",
    "FALL",
    "FAN",
    "FENCE",
    "FIELD",
    "FIGHTER",
    "FIGURE",
    "FILE",
    "FILM",
    "FIRE",
    "FISH",
    "FLUTE",
    "FLY",
    "FOOT",
    "FORCE",
    "FOREST",
    "FORK",
    "FRANCE",
    "GAME",
    "GAS",
    "GENIUS",
    "GERMANY",
    "GHOST",
    "GIANT",
    "GLASS",
    "GLOVE",
    "GOLD",
    "GRACE",
    "GRASS",
    "GREECE",
    "GREEN",
    "GROUND",
    "HAM",
    "HAND",
    "HAWK",
    "HEAD",
    "HEART",
    "HELICOPTER",
    "HIMALAYAS",
    "HOLE",
    "HOLLYWOOD",
    "HONEY",
    "HOOD",
    "HOOK",
    "HORN",
    "HORSE",
    "HORSESHOE",
    "HOSPITAL",
    "HOTEL",
    "ICE",
    "ICE CREAM",
    "INDIA",
    "IRON",
    "IVORY",
    "JACK",
    "JAM",
    "JET",
    "JUPITER",
    "KANGAROO",
    "KETCHUP",
    "KEY",
    "KID",
    "KING",
    "KIWI",
    "KNIFE",
    "KNIGHT",
    "LAB",
    "LAP",
    "LASER",
    "LAWYER",
    "LEAD",
    "LEMON",
    "LEPRECHAUN",
    "LIFE",
    "LIGHT",
    "LIMOUSINE",
    "LINE",
    "LINK",
    "LION",
    "LITTER",
    "LOCH NESS",
    "LOCK",
    "LOG",
    "LONDON",
    "LUCK",
    "MAIL",
    "MAMMOTH",
    "MAPLE",
    "MARBLE",
    "MARCH",
    "MASS",
    "MATCH",
    "MERCURY",
    "MEXICO",
    "MICROSCOPE",
    "MILLIONAIRE",
    "MINE",
    "MINT",
    "MISSILE",
    "MODEL",
    "MOLE",
    "MOON",
    "MOSCOW",
    "MOUNT",
    "MOUSE",
    "MOUTH",
    "MUG",
    "NAIL",
    "NEEDLE",
    "NET",
    "NEW YORK",
    "NIGHT",
    "NINJA",
    "NOTE",
    "NOVEL",
    "NURSE",
    "NUT",
    "OCTOPUS",
    "OIL",
    "OLIVE",
    "OLYMPUS",
    "OPERA",
    "ORANGE",
    "ORGAN",
    "PALM",
    "PAN",
    "PANTS",
    "PAPER",
    "PARACHUTE",
    "PARK",
    "PART",
    "PASS",
    "PASTE",
    "PENGUIN",
    "PHOENIX",
    "PIANO",
    "PIE",
    "PILOT",
    "PIN",
    "PIPE",
    "PIRATE",
    "PISTOL",
    "PIT",
    "PITCH",
    "PLANE",
    "PLASTIC",
    "PLATE",
    "PLATYPUS",
    "PLAY",
    "PLOT",
    "POINT",
    "POISON",
    "POLE",
    "POLICE",
    "POOL",
    "PORT",
    "POST",
    "POUND",
    "PRESS",
    "PRINCESS",
    "PUMPKIN",
    "PUPIL",
    "PYRAMID",
    "QUEEN",
    "RABBIT",
    "RACKET",
    "RAY",
    "REVOLUTION",
    "RING",
    "ROBIN",
    "ROBOT",
    "ROCK",
    "ROME",
    "ROOT",
    "ROSE",
    "ROULETTE",
    "ROUND",
    "ROW",
    "RULER",
    "SATELLITE",
    "SATURN",
    "SCALE",
    "SCHOOL",
    "SCIENTIST",
    "SCORPION",
    "SCREEN",
    "SCUBA DIVER",
    "SEAL",
    "SERVER",
    "SHADOW",
    "SHAKESPEARE",
    "SHARK",
    "SHIP",
    "SHOE",
    "SHOP",
    "SHOT",
    "SINK",
    "SKYSCRAPER",
    "SLIP",
    "SLUG",
    "SMUGGLER",
    "SNOW",
    "SNOWMAN",
    "SOCK",
    "SOLDIER",
    "SOUL",
    "SOUND",
    "SPACE",
    "SPELL",
    "SPIDER",
    "SPIKE",
    "SPINE",
    "SPOT",
    "SPRING",
    "SPY",
    "SQUARE",
    "STADIUM",
    "STAFF",
    "STAR",
    "STATE",
    "STICK",
    "STOCK",
    "STRAW",
    "STREAM",
    "STRIKE",
    "STRING",
    "SUB",
    "SUIT",
    "SUPERHERO",
    "SWING",
    "SWITCH",
    "TABLE",
    "TABLET",
    "TAG",
    "TAIL",
    "TAP",
    "TEACHER",
    "TELESCOPE",
    "TEMPLE",
    "THEATER",
    "THIEF",
    "THUMB",
    "TICK",
    "TIE",
    "TIME",
    "TOKYO",
    "TOOTH",
    "TORCH",
    "TOWER",
    "TRACK",
    "TRAIN",
    "TRIANGLE",
    "TRIP",
    "TRUNK",
    "TUBE",
    "TURKEY",
    "UNDERTAKER",
    "UNICORN",
    "VACUUM",
    "VAN",
    "VET",
    "WAKE",
    "WALL",
    "WAR",
    "WASHER",
    "WASHINGTON",
    "WATCH",
    "WATER",
    "WAVE",
    "WEB",
    "WELL",
    "WHALE",
    "WHIP",
    "WIND",
    "WITCH",
    "WORM",
    "YARD",
  ];
  // These are the problem pieces of code
  const scoreUpdaterInc = (tile: Tile) => {
    if (tile.id === 1) {
      setRedScore(redScore + 1);
    } else if (tile.id === 2) {
      setBlueScore(blueScore + 1);
    } else {
    }
  };

  console.log(`red Score is ${redScore}`);
  console.log(`blue Score is ${blueScore}`);

  const startGameHandler = () => {
    setStartClicked(!startClicked);
  };

  const newGameList = () => {
    setGameList(shuffledWordList.splice(0, 25));
  };
  useEffect(() => {
    setShuffledWordList(
      masterWordList
        .map((word) => ({
          word,
          key: Math.random(),
        }))
        .sort((a, b) => a.key - b.key)
        .map(({ word }) => word)
    );
  }, []);

  return (
    <div className="Main">
      <div>
        <ul className="tiles">
          {tiles.map((tile) => (
            <ColorTile color={tile.color} id={tile.id} />
          ))}
        </ul>
        <ul className="color-tile-names">
          {team1.teamColor === "red" ? (
            <li>{team1.teamName}</li>
          ) : (
            <li>{team2.teamName}</li>
          )}
          {team1.teamColor === "blue" ? (
            <li>{team1.teamName}</li>
          ) : (
            <li>{team2.teamName}</li>
          )}
          <li>Bystander</li>
          <li>Assassin</li>
        </ul>
        <ul className="game-board">
          {gameList.map((word) => (
            <li key={Math.random()}>
              <WordTile
                word={word}
                tiles={tiles}
                scoreUpdaterInc={scoreUpdaterInc}
              />
            </li>
          ))}
        </ul>
      </div>
      {startClicked && (
        <TeamForm
          setTeam1={setTeam1}
          setTeam2={setTeam2}
          newGameList={newGameList}
          setStartClicked={setStartClicked}
        />
      )}
      <button onClick={startGameHandler}>Start Game</button>
    </div>
  );
};

export default Main;
